# This is the Snakemake configuration file that specifies paths and 
# and options for the pipeline. Anybody wishing to use
# the provided snakemake pipeline should first fill out this file with paths to
# their own data, as the Snakefile requires it.
# All paths are relative to the directory that Snakemake is executed in.
# Note: this file is written in the YAML syntax (https://learnxinyminutes.com/docs/yaml/)


# Path to each motif dataset
# You must provide both the original ChIP-seq BED file and the motifs in JASPAR format
data:
  ctcf:
    peaks: data/ctcf/ENCFF023LAA.nochr.bed.gz
    motifs: data/ctcf/ctcf-chip-seq-ENCSR000BNH.jaspar
  ctcf_no-pretrain:
    peaks: data/ctcf/ENCFF023LAA.nochr.bed.gz
    motifs: data/ctcf/ctcf-chip-seq-ENCSR000BNH_no-pretrain.jaspar
  nrf1:
    peaks: data/nrf1/nrf1_data/ENCFF182QJW.nochr.bed.gz
    motifs: data/nrf1/nrf1_dman/ENCFF182QJW.wide.scored.jaspar
  nrf1_homer:
    peaks: data/nrf1/nrf1_data/ENCFF182QJW.nochr.bed.gz
    motifs: data/nrf1_homer/homerMotifs.all.pfm.fixed2.jaspar

# Path to a reference genome for the experiments
ref: /gpfs/data01/bennerlab/species/genomes/homo_sapiens/genome.fa

# Which widths should be used when labeling the center hits as positives?
widths: [100, 150, 200, 300]

# What threshold should be used on the scoring function when outputting metrics?
score_thresh: 7.5

# A threshold on the adjusted p-value from meirlop. All other motifs with higher p-vals
# will be discarded
pval_thresh: 0.01

# Path to the results/output folder
# This is usually overridden by whatever is in the run.bash script
out: out
